# 다중 선형회귀
## 보스톤 집값

In [1]:
import numpy as np
import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from sklearn.model_selection import train_test_split

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# seed 값 생성
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
df = pd.read_csv("dataset/housing.csv", delim_whitespace=True, header=None)
dataset = df.values
x_data = np.array(dataset[:,0:13], dtype=np.float64)
y_data = np.array(dataset[:,13], dtype=np.float64).reshape(506,1)
print(x_data.shape, y_data.shape)

(506, 13) (506, 1)


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(x_data, y_data, test_size=0.3, 
                                                    random_state=seed)

In [22]:
# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float64, shape=[None, 13])
Y = tf.placeholder(tf.float64, shape=[None, 1])

In [23]:
# Layer 1
W1 = tf.Variable(tf.random_normal([13,30], dtype=tf.float64)) 
b1 = tf.Variable(tf.random_normal([30], dtype=tf.float64))
L1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1))
#L1 = tf.add(tf.matmul(X, W1), b1)

In [24]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,6], dtype=tf.float64)) 
b2 = tf.Variable(tf.random_normal([6], dtype=tf.float64))
L2 = tf.nn.relu(tf.add(tf.matmul(L1, W2), b2))
#L2 = tf.add(tf.matmul(L1, W2), b2)

In [25]:
# Layer 3
W3 = tf.Variable(tf.random_normal([6,1], dtype=tf.float64)) 
b3 = tf.Variable(tf.random_normal([1], dtype=tf.float64))
hypo = tf.add(tf.matmul(L2, W3), b3)

In [26]:
# Mean Squared Error
cost = tf.reduce_mean(tf.square(Y - hypo))

In [27]:
learning_rate = 0.1
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [30]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(2001):
    sess.run(train, feed_dict = {X: X_train, Y: Y_train})
    if epoch % 100 == 0:
        cost_val = sess.run(cost, feed_dict = {X: X_train, Y: Y_train})
        print("step=%d, \tcost_val=%.5f" % (epoch + 1, cost_val))
    
W1_, W2_, W3_, b1_, b2_, b3_ = sess.run([W1, W2, W3, b1, b2, b3])

step=1, 	cost_val=1172499.89921
step=101, 	cost_val=17288.43353
step=201, 	cost_val=6089.22396
step=301, 	cost_val=1988.69773
step=401, 	cost_val=888.47845
step=501, 	cost_val=554.94184
step=601, 	cost_val=378.35750
step=701, 	cost_val=258.67922
step=801, 	cost_val=177.24331
step=901, 	cost_val=123.43093
step=1001, 	cost_val=88.67077
step=1101, 	cost_val=66.52679
step=1201, 	cost_val=52.52968
step=1301, 	cost_val=43.72700
step=1401, 	cost_val=38.21414
step=1501, 	cost_val=34.76839
step=1601, 	cost_val=32.60289
step=1701, 	cost_val=31.21252
step=1801, 	cost_val=30.27765
step=1901, 	cost_val=29.60147
step=2001, 	cost_val=29.06732


In [20]:
X_test[0,:], Y_test[0]

(array([[6.7240e-02],
        [0.0000e+00],
        [3.2400e+00],
        [0.0000e+00],
        [4.6000e-01],
        [6.3330e+00],
        [1.7200e+01],
        [5.2146e+00],
        [4.0000e+00],
        [4.3000e+02],
        [1.6900e+01],
        [3.7521e+02],
        [7.3400e+00]]), array([22.6]))

In [54]:
hypo_val = sess.run(hypo, feed_dict = {X: X_test[10,:].reshape(1,13)})
hypo_val[0].item()

22.28272213526217

In [35]:
real = float(Y_test[0].item())
type(real)

float

In [32]:
for i in range(10):
    hypo_val = sess.run(hypo, feed_dict = {X: X_test[i,:].reshape(1,13)})
    real = float(Y_test[i].item())
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(real, hypo_val[0].item()))

실제가격: 22.600, 예상가격: 21.737
실제가격: 50.000, 예상가격: 24.438
실제가격: 23.000, 예상가격: 28.719
실제가격: 8.300, 예상가격: 13.764
실제가격: 21.200, 예상가격: 19.915
실제가격: 19.900, 예상가격: 23.630
실제가격: 20.600, 예상가격: 19.285
실제가격: 18.700, 예상가격: 23.574
실제가격: 16.100, 예상가격: 16.876
실제가격: 18.600, 예상가격: 21.166


In [14]:
def ReLU(x):
    return x * (x > 0)

In [15]:
L1_ = ReLU(np.matmul(X_test[0,:].reshape(1,13), W1_) + b1_)
L1_

array([[1026.23829698,   -0.        ,  171.87386865,   -0.        ,
         910.37609293,   -0.        ,   -0.        ,  385.50032964,
          -0.        ,   -0.        ,  481.81291107,   -0.        ,
          -0.        ,   -0.        ,   -0.        ,   -0.        ,
        1504.30751992,   -0.        ,   -0.        ,   -0.        ,
          -0.        ,   -0.        ,   -0.        ,  562.77518204,
          -0.        ,  311.44563972,   -0.        ,   -0.        ,
         224.98064201,   -0.        ]])

In [19]:
L2_ = ReLU(np.matmul(L1_, W2_) + b2_)
L2_

array([[-0., -0., -0., -0., -0., -0.]])

In [20]:
H = np.matmul(L2_, W3_) + b3_
H

array([[22.28272214]])

In [4]:
model = Sequential([
    Dense(30, input_dim=13, activation='relu'),
    Dense(6, activation='relu'),
    Dense(1)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 30)                420       
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 186       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 613
Trainable params: 613
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [7]:
model.fit(X_train, Y_train, epochs=200, batch_size=10)

Train on 354 samples
Epoch 1/200
354/354 [==============================] - 1s 3ms/sample - loss: 8288.7038
Epoch 2/200
354/354 [==============================] - 0s 318us/sample - loss: 670.3084
Epoch 3/200
354/354 [==============================] - 0s 310us/sample - loss: 498.1093
Epoch 4/200
354/354 [==============================] - 0s 327us/sample - loss: 379.1674
Epoch 5/200
354/354 [==============================] - 0s 386us/sample - loss: 252.3767
Epoch 6/200
354/354 [==============================] - 0s 414us/sample - loss: 166.6476
Epoch 7/200
354/354 [==============================] - 0s 406us/sample - loss: 135.1676
Epoch 8/200
354/354 [==============================] - 0s 394us/sample - loss: 123.5331
Epoch 9/200
354/354 [==============================] - 0s 378us/sample - loss: 115.3392
Epoch 10/200
354/354 [==============================] - 0s 347us/sample - loss: 93.0773
Epoch 11/200
354/354 [==============================] - 0s 335us/sample - loss: 76.3689
Epoch 12/200

354/354 [==============================] - 0s 369us/sample - loss: 19.1292
Epoch 186/200
354/354 [==============================] - 0s 380us/sample - loss: 18.2614
Epoch 187/200
354/354 [==============================] - 0s 380us/sample - loss: 17.2866
Epoch 188/200
354/354 [==============================] - 0s 389us/sample - loss: 17.1631
Epoch 189/200
354/354 [==============================] - 0s 406us/sample - loss: 16.9712
Epoch 190/200
354/354 [==============================] - 0s 355us/sample - loss: 17.2057
Epoch 191/200
354/354 [==============================] - 0s 324us/sample - loss: 18.2261
Epoch 192/200
354/354 [==============================] - 0s 347us/sample - loss: 22.7555
Epoch 193/200
354/354 [==============================] - 0s 355us/sample - loss: 16.9408
Epoch 194/200
354/354 [==============================] - 0s 332us/sample - loss: 16.6988
Epoch 195/200
354/354 [==============================] - 0s 321us/sample - loss: 16.5898
Epoch 196/200
354/354 [============

In [8]:
# 예측 값과 실제 값의 비교
Y_prediction = model.predict(X_test).flatten()
for i in range(10):
    label = Y_test[i]
    prediction = Y_prediction[i]
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(label, prediction))

실제가격: 22.600, 예상가격: 24.907
실제가격: 50.000, 예상가격: 24.968
실제가격: 23.000, 예상가격: 24.454
실제가격: 8.300, 예상가격: 11.499
실제가격: 21.200, 예상가격: 17.799
실제가격: 19.900, 예상가격: 20.584
실제가격: 20.600, 예상가격: 22.514
실제가격: 18.700, 예상가격: 21.913
실제가격: 16.100, 예상가격: 16.251
실제가격: 18.600, 예상가격: 8.082
