## 다중 로지스틱 회귀 - Tensorflow 2.0
- 변수 2개: 학습 시간, 과외 횟수

| 합격여부 (Y) | 0 | 0 | 0 | 1 |  1 |  1 |  1 |
|:---:|---:|---:|---:|---:|---:|---:|---:|
| 학습시간 (X1) | 2 | 4 | 6 | 8 | 10 | 12 | 14 |
| 과외횟수 (X2) | 3 | 3 | 4 | 6 |  7 |  8 |  9 |

In [1]:
# 필요한 라이브러리
import numpy as np
import tensorflow as tf

In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [3]:
# x, y의 데이터 값
x_train = np.array([[2, 3],[4, 3],[6, 4],[8, 6],[10, 7],[12, 8],[14, 9]]) 
y_train = np.array([0, 0, 0, 1, 1, 1, 1]).reshape(7, 1)

### Stochastic Gradient Descent Optimizer

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid')
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [7]:
history = model.fit(x_train, y_train, epochs=5000, verbose=0)

In [8]:
new_x = np.array([7, 6.]).reshape(1, 2) 
model.predict(new_x)

array([[0.5009885]], dtype=float32)

### Root Mean Square Propagation

In [9]:
model2 = tf.keras.models.Sequential([
  tf.keras.layers.Dense(1, input_shape=(2,), activation='sigmoid')
])

In [10]:
model2.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [11]:
history2 = model2.fit(x_train, y_train, epochs=5000, verbose=0)

In [12]:
new_x = np.array([7, 6.]).reshape(1, 2) 
model2.predict(new_x)

array([[0.6735452]], dtype=float32)

In [16]:
dir(model2)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_inbound_node',
 '_add_trackable',
 '_add_unique_metric_name',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_attribute_sentinel',
 '_autocast',
 '_base_init',
 '_build_input_shape',
 '_build_model_with_inputs',
 '_cache_output_metric_attributes',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_args',
 '_call_full_argspec',
 '_callable_losses',
 '_check_call_args',
 '_check_trainable_weights_consistency',
 '_checkpoint_dependencies',
 '_clear_losse

In [17]:
model2.weights

[<tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.44816354],
        [0.35177606]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([-4.523537], dtype=float32)>]

### 계산으로 확인

In [13]:
m1 = np.array([7, 6.]).reshape(1, 2)
m1.shape

(1, 2)

In [14]:
m2 = np.array([0.1779, 1.5675]).reshape(2, 1)
m2.shape

(2, 1)

In [15]:
np.matmul(m1, m2)

array([[10.6503]])

In [17]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [18]:
print(sigmoid(10.6503 - 8.8635))

0.8565344988956533
