## 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [4]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0])
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4,)


array([0, 1, 1, 0])

In [5]:
y_data = y_data.reshape(4,1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [36]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [37]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [38]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [39]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [40]:
# Optimizer - Adam
lr = 0.03
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [41]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [42]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    w1val, b1val, w2val, b2val = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{w1val} \nb1:\n{b1val} \nW2:\n{w2val}\nb1:\n{b2val}")

0 0.6936492
1000 0.34796694
2000 0.34696352
3000 0.34674114
4000 0.34665823
5000 0.34662002
6000 0.34660053
7000 0.34659028
8000 0.3465845
9000 0.34658056
10000 0.3465784

Hypothesis:
[[7.2716152e-06]
 [4.9999738e-01]
 [9.9999619e-01]
 [5.0000143e-01]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [1.]] 
Accuracy:
0.5

W1:
[[ 7.633429  -7.4882274]
 [16.89402   16.765081 ]] 
b1:
[-2.7802656  5.1402936] 
W2:
[[ 12.6504545]
 [-13.766144 ]]
b1:
[1.1156874]
